### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by g4s8** [cqfn/degitx#45]
Implement node logging. Let's discuss and specify the format of log messages, it definitely should include node id, timestamp, layer of protocol (tag), log level, message. Timestamp should be printed in some well known format to be parsed later automatically.

Example: `INFO 2020-10-10T19:30:46.123Z 0123456abc[Discovery]  Found new node abc3456 at /ipv4/1.2.3.4/tcp/145` where the format was `<level> <timestamp> <locator>[<tag>] <message>\n`.

Implement logging API then. Please discuss before implementing.

**Comment by stepanvalyavskiy** [comment]
Hi, @g4s8, I have compared and tried several loggers, and I suggest to consider [zap](https://github.com/uber-go/zap). Its has best [perfomance](https://github.com/uber-go/zap#performance) and very powerful.

**pros:**
 - strongly-typed, structured logging, It is faster and allocates far less then analogs
- build-in json & console encoder
 - new encoders could be easily added
- could write to console, files and urls
- suggard version with printf-like methods
- configurable
**cons:**
 - doesn't has TRACE level
 - dpanic, panic, fatal instead of CRITICAL. all 3 levels also perform some actions after logging: `panic` or `os.Exit(1)` 

please have a look at my [draft implementation](https://github.com/stepanvalyavskiy/degitx/commit/dfc056352ac55f37af0a0c0de3cb198780617cfb)

It's configured so to write all enabled log levels below ERROR in stdout in `console` format:
```
2020-10-26T06:39:55.023+0300    INFO    LOG MESSAGE    {"tag":"discovery", "locator":"stub"}
```
and all enabled log levels starting from ERROR and above both in stderr in `console` format: 
```diff
- 2020-10-26T06:39:55.023+0300    ERROR    LOG MESSAGE    {"tag":"discovery", "locator":"stub"}
```
and in `./error` file in `json` format:
```
{"Level":"ERROR","Time":"2020-10-26T06:39:55.023+0300","Message":"LOG MESSAGE","tag":"discovery","locator":"stub"}
````

**Comment by g4s8** [comment]
@stepanvalyavskiy thanks, looks like a good choice. About log format, I'd keep it similar console and file: e.g. 
`2020-10-26T06:39:55.023+0300    INFO {"message": "msg", "tag": "sometag", "locator": "any"}`.
We'll have really huge amount of logs in production, and we'll have to filter by levlel and timestamp very fast, so json parsing may be expensive operation for such amount of log messages, so I'd keep it in predefined order before json body

**Comment by stepanvalyavskiy** [comment]
Hi, @g4s8, API is ready, I also think we need to discuss and do config file.
I suggest yaml smth like:
```yaml
log_level: INFO
log_format: plain or json
output_low_priority: 
  - stdout
  - "./log"
  - "some url"
output_high_priority:
  - stderr
  - "./error_log"
  - "some url"
```

**Comment by g4s8** [comment]
@stepanvalyavskiy I didn't get what is high and low priority, I think we need to have multiple outputs with different filters, e.g.:
```yaml
logging:
  outputs:
   - type: stdout
     leve: DEBUG
     format: plain
   - type: file
     filename: /var/log/degitx.log
     format: json
     level: INFO
   - type: remote
     endpoint: http://logging.service/
     level: WARNING
     format: json
```
